apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: edu/service-a:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SERVICE_A_URL
              value: "http://service-a:8080"
